# Site settings
title: SortingBubblesHelp
email: ntemposd@gmail.com
description: >
    Get involved with the Campus initiatives at Thess
baseurl: ""
url: "githubpages-boilerplate"
twitter_username: ntemposd
github_username:  ntemposd

# Build settings
markdown: kramdown

include: ['_pages']
